name: Mutation Test Generation Workflow
on:
  push

jobs:
  mutation-test-generation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run forge install
        run: forge install

      - name: Get added, renamed, modified Solidity Files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            src/**/*.sol

      - name: Debug changed files output
        run: echo "Changed files flag: ${{ steps.changed-files.outputs.all_changed_files }}"

      - name: Debug changed files output
        run: echo "Changed files flag: ${{ steps.changed-files.outputs.any_changed }}"

      - name: Convert Changed Files to Args
        if: steps.changed-files.outputs.any_changed == 'true'
        id: format-args
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          IFS=$'\n' read -rd '' -a filesArray <<< "$ALL_CHANGED_FILES"
          if [ "${#filesArray[@]}" -gt 5 ]; then
            echo "Warning: More than 5 .sol files changed. Only using the first 5."
            filesArray=("${filesArray[@]:0:5}")
          fi

          args=$(printf -- "-p %s " "${filesArray[@]}")
          echo "ARGS=$args" >> $GITHUB_ENV

      - name: Mutation Test Generator
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: olympix/mutation-test-generator@main
        env:
          OLYMPIX_API_TOKEN: ${{ secrets.OLYMPIX_API_TOKEN }}
          OLYMPIX_GITHUB_ACCESS_TOKEN: ${{ secrets.GH_PAT }}
        with:
          args: ${{ env.ARGS }}